// ログ読解道場: ログ断片から状況を読み取る4択
window.DRILL_DATA = {
  title: "ログ読解道場",
  desc: "実ログ風の断片から「何が起きているか」を読み取る訓練です。",
  questions: [
    { q: "nginxアクセスログ:\n`192.168.10.5 - - [06/Jul/2026:09:12:01 +0900] \"GET /index.html HTTP/1.1\" 200 5120`\nこのリクエストの結果は?",
      choices: ["正常に応答した", "ページが見つからなかった", "サーバー内部エラー", "認証が必要だった"], answer: 0,
      fb: "ステータス200=成功。5120は応答サイズ(バイト)" },
    { q: "nginxアクセスログのステータスが `404` 。意味は?",
      choices: ["リクエストされたパスが存在しない", "サーバー内部エラー", "アクセス権限がない", "リダイレクトされた"], answer: 0,
      fb: "404 Not Found。403は権限拒否、500系はサーバー側エラー、301/302はリダイレクト" },
    { q: "nginxエラーログ:\n`connect() failed (111: Connection refused) while connecting to upstream, upstream: \"http://127.0.0.1:9000\"`\n最も疑うべきは?",
      choices: ["背後のアプリ(PHP-FPM等)が起動していない", "nginx自体が停止している", "クライアントのネットワーク断", "ディスクフル"], answer: 0,
      fb: "upstream(転送先)への接続拒否=バックエンド停止が典型。502 Bad Gateway とセットで出ます" },
    { q: "`/var/log/auth.log` に\n`Failed password for root from 203.0.113.50 port 51234 ssh2` が数千行。何が起きている?",
      choices: ["SSHへのブルートフォース攻撃を受けている", "rootのパスワード期限切れ", "SSHサービスの故障", "正常なログ"], answer: 0,
      fb: "総当たり攻撃の典型。対策は鍵認証化・rootログイン禁止・fail2ban等" },
    { q: "syslog:\n`kernel: Out of memory: Killed process 1234 (mysqld)`\n何が起きた?",
      choices: ["メモリ不足でOSがMySQLを強制終了した", "MySQLが正常にシャットダウンした", "ディスク故障", "CPU過熱"], answer: 0,
      fb: "OOM Killer。メモリ増設・チューニング・他プロセスの整理を検討します" },
    { q: "`df -h` で `/dev/sda2 100% /` と表示。直後に各サービスが書き込みエラー。原因は?",
      choices: ["ルートファイルシステムのディスクフル", "CPU使用率100%", "メモリ枯渇", "inode以外は正常なので無関係"], answer: 0,
      fb: "使用率100%=空き0。ログ肥大が定番原因。duで犯人を探しlogrotateを設定" },
    { q: "systemd:\n`nginx.service: Failed to start ... code=exited, status=1`\n次に打つべきコマンドは?",
      choices: ["`journalctl -xeu nginx` で詳細ログを見る", "すぐOSを再起動する", "nginxを再インストールする", "ディスクを交換する"], answer: 0,
      fb: "起動失敗はまず詳細ログ。nginxなら `nginx -t` の構文チェックも定石" },
    { q: "Windowsイベントログで「ソース: disk, ID: 7」(不良ブロック)が繰り返し記録。対応は?",
      choices: ["バックアップを確認しディスク交換を計画する", "ログを消して様子見", "メモリを増設する", "ウイルススキャンだけ実施"], answer: 0,
      fb: "不良ブロックの繰り返しは故障前兆。データ保全が最優先" },
    { q: "アクセスログで深夜に `POST /wp-login.php` が1秒間に10回×2時間続いている。これは?",
      choices: ["管理画面へのパスワード総当たり攻撃", "検索エンジンのクロール", "バックアップ処理", "正常なユーザーアクセス"], answer: 0,
      fb: "ログイン試行の高頻度連打は攻撃。IP制限やWAF、レート制限を検討" },
    { q: "メールサーバーのログ:\n`554 5.7.1 Service unavailable; Client host blocked using zen.spamhaus.org`\n意味は?",
      choices: ["自社のIPがブラックリストに載り受信拒否された", "相手サーバーの故障", "添付ファイルが大きすぎた", "宛先アドレスの打ち間違い"], answer: 0,
      fb: "DNSBLによるブロック。リスト掲載理由(踏み台化等)の調査と解除申請が必要" },
    { q: "ログのタイムスタンプが `Jul  6 09:00:00` から `Jul  6 09:47:12` へ突然47分飛んでいる。まず疑うのは?",
      choices: ["その間サーバーが停止/フリーズしていた", "ログが改ざんされた", "タイムゾーン設定ミス", "正常(ログは間引かれるもの)"], answer: 0,
      fb: "無音区間は停止の痕跡。直前の最後のログが原因調査の手がかり" },
    { q: "`sudo: taro : user NOT in sudoers ; command=/usr/bin/systemctl restart nginx`\n何が起きた?",
      choices: ["権限のないユーザーがsudoで管理コマンドを実行しようとした", "nginxが再起動ループしている", "taroのパスワード間違い", "sudoコマンドの故障"], answer: 0,
      fb: "sudoers未登録ユーザーの実行試行。本人確認と、必要なら権限付与プロセスへ" },
    { q: "アクセスログのステータス `301` が大量。意味は?",
      choices: ["恒久的リダイレクト(移転先へ誘導)", "認証エラー", "サーバーエラー", "アクセス禁止"], answer: 0,
      fb: "301 Moved Permanently。http→https誘導などで正常に出ることも多い" },
    { q: "journalctl:\n`Certificate has expired` とともにHTTPS接続エラーが多発。対応は?",
      choices: ["SSL証明書を更新する(自動更新の失敗原因も確認)", "サーバーを再起動する", "DNSを変更する", "ファイアウォールを開放する"], answer: 0,
      fb: "証明書期限切れ。Let's Encryptなら自動更新(certbot renew)の失敗理由まで直すこと" },
  ]
};
