// 1-2 OSの役割 章末クイズ
window.QUIZ_DATA = {
  id: "part1-ch02",
  title: "1-2 OSの役割 章末クイズ",
  passLine: 70,
  questions: [
    { type: "multi", level: 1,
      q: "OSの4つの仕事に含まれるものをすべて選んでください。",
      choices: ["プロセス管理", "メモリ管理", "ファイルシステム管理", "Webサイトのデザイン"],
      answer: [0, 1, 2],
      explain: "OSの仕事は「プロセス・メモリ・ファイルシステム・デバイス」の4管理。アプリの機能(デザイン等)はOSの仕事ではありません。" },
    { type: "single", level: 1,
      q: "「実行中のプログラム」を指すOS用語はどれですか?",
      choices: ["プロセス", "ドライバー", "パーティション", "レジストリ"],
      answer: [0],
      explain: "実行中のプログラム=プロセス。タスクマネージャーや `ps` コマンドで見えるのはプロセスの一覧です。" },
    { type: "single", level: 2,
      q: "メモリが不足したとき、OSがディスクの一部を「仮の机」として使う仕組みを何と呼びますか?",
      choices: ["仮想メモリ(スワップ)", "キャッシュメモリ", "RAID", "デフラグ"],
      answer: [0],
      explain: "仮想メモリ(スワップ)。ディスクはメモリより桁違いに遅いため、スワップ多発=体感速度の急落。「メモリ増設で速くなる」根拠です。" },
    { type: "single", level: 2,
      q: "Windowsの標準ファイルシステムはどれですか?",
      choices: ["NTFS", "APFS", "ext4", "FAT12"],
      answer: [0],
      explain: "WindowsはNTFS(アクセス権や暗号化に対応)。APFSはmacOS、ext4はLinuxの定番です。USBメモリは互換性のためexFAT等が使われます。" },
    { type: "single", level: 2,
      q: "会社のPCとしてWindows「Home」エディションが不適切な最大の理由はどれですか?",
      choices: [
        "ドメイン参加やGPOによる統制ができないから",
        "Officeがインストールできないから",
        "インターネットに接続できないから",
        "ウイルス対策ソフトが動かないから"],
      answer: [0],
      explain: "HomeはAD(ドメイン)参加不可・GPO不可・BitLocker管理不可。会社の統制に乗せられません。Office等のアプリは動作します。" },
    { type: "single", level: 1,
      q: "Linuxが最も多く使われている場所はどれですか?",
      choices: ["サーバー", "会社の事務用デスクトップPC", "ゲーム専用機の店頭デモ", "電卓"],
      answer: [0],
      explain: "Webサーバーをはじめサーバー分野はLinuxが主流。だから情シスもLinuxを学びます(Part 3)。" },
    { type: "single", level: 3,
      q: "社員から「USBメモリをMacで使ったらWindowsで読めなくなった」と相談されました。最も可能性が高い原因はどれですか?",
      choices: [
        "Mac側でAPFS等のWindows非対応形式でフォーマットした",
        "USBメモリがウイルスに感染した",
        "WindowsのUSBポートの故障",
        "USBメモリの寿命"],
      answer: [0],
      explain: "OSごとにファイルシステムが違うため、Mac専用形式でフォーマットするとWindowsで読めません。両対応にするならexFATでフォーマットします。" },
    { type: "single", level: 2,
      q: "「ドライバー」の役割として正しいものはどれですか?",
      choices: [
        "OSが周辺機器を制御するための橋渡しソフトウェア",
        "PCの持ち運び用ハンドル",
        "ファイルを圧縮するソフトウェア",
        "CPUの冷却装置"],
      answer: [0],
      explain: "ドライバーはOSとデバイスの通訳。プリンターが動かない時に「ドライバー入れ直し」が効くのは、この通訳を修復しているからです。" },
  ]
};
