// 3-9 SSHとファイル転送 章末クイズ
window.QUIZ_DATA = {
  id: "part3-ch09",
  title: "3-9 SSHとファイル転送 章末クイズ",
  passLine: 70,
  questions: [
    { type: "single", level: 1,
      q: "公開鍵認証で「サーバーに置く」ものはどちらですか?",
      choices: ["公開鍵(id_ed25519.pub)", "秘密鍵(id_ed25519)", "両方", "どちらも置かない"],
      answer: [0],
      explain: "公開鍵=南京錠はサーバーのauthorized_keysへ。秘密鍵=鍵は手元厳守。逆にすると認証は成立せず、秘密鍵漏えい事故になります。" },
    { type: "single", level: 2,
      q: "鍵を登録したのにパスワードを聞かれます。サーバー側で最初に確認すべきはどれですか?",
      choices: [
        "~/.ssh が700、authorized_keys が600になっているか",
        "サーバーのメモリ残量",
        "モニターの解像度",
        "nginxのバージョン"],
      answer: [0],
      explain: "パーミッションが緩いとsshdは鍵認証を拒否します。「鍵を入れたのに入れない」原因の第1位です。" },
    { type: "single", level: 3,
      q: "sshd_configで PasswordAuthentication no に変更する際の、事故らない手順はどれですか?",
      choices: [
        "既存のSSHセッションを維持したまま、別ターミナルで新規接続テストをしてから既存を閉じる",
        "変更後すぐ全セッションを閉じて再接続で確認する",
        "設定変更と同時にOSを再起動する",
        "検証は不要、設定は必ず正しいから"],
      answer: [0],
      explain: "失敗しても既存セッションから戻せる状態を保つのが鉄則。自分を締め出すのが「SSH三大事故」の筆頭です。" },
    { type: "single", level: 2,
      q: "何度も繰り返す大量ファイルの同期に適したコマンドはどれですか?",
      choices: ["rsync(差分だけ転送する)", "scp(毎回全量コピー)", "cat", "ping"],
      answer: [0],
      explain: "rsyncは2回目以降、変更分だけを転送。単発ならscpで十分です。--deleteは削除も同期する強力オプションなので要注意。" },
    { type: "single", level: 2,
      q: "PermitRootLogin no を設定する理由として最も適切なのはどれですか?",
      choices: [
        "最強権限のrootが直接攻撃対象になるのを防ぎ、個人アカウント経由で操作履歴を残すため",
        "rootではviが動かないから",
        "パスワードが長くなるから",
        "SSHが高速になるから"],
      answer: [0],
      explain: "rootは全サーバー共通のユーザー名なので総当たり攻撃の第一標的。個人ID+sudoなら「誰がやったか」も追えます。" },
    { type: "fill", level: 2,
      q: "手元の report.txt をサーバー(lab01)の /tmp/ へコピーするscpコマンドを書いてください(接続名lab01を使用)。",
      answer: ["scp report.txt lab01:/tmp/", "scp ./report.txt lab01:/tmp/", "scp report.txt lab01:/tmp"],
      explain: "`scp コピー元 接続先:パス`。~/.ssh/config で接続名を定義しておくと、この短さで書けます。" },
  ]
};
