// 3-1 Linuxとは 章末クイズ
window.QUIZ_DATA = {
  id: "part3-ch01",
  title: "3-1 Linuxとは 章末クイズ",
  passLine: 70,
  questions: [
    { type: "single", level: 1,
      q: "「カーネル」と「ディストリビューション」の関係として正しいものはどれですか?",
      choices: [
        "カーネルはOSの芯で、それにコマンド群やパッケージ管理を束ねた配布形がディストリビューション",
        "カーネルはGUIの名前で、ディストリはCUIの名前",
        "両者は同じものの別名",
        "ディストリビューションはWindowsの機能"],
      answer: [0],
      explain: "Linuxカーネル+周辺ツールをまとめて使いやすくしたものがUbuntu等のディストリです。" },
    { type: "single", level: 1,
      q: "Ubuntuが属する系統はどれですか?",
      choices: ["Debian系", "RHEL系", "BSD系", "Windows系"],
      answer: [0],
      explain: "UbuntuはDebian系(apt/.deb)。RHEL系はdnf/.rpmで、AlmaLinux/Rocky Linuxが互換OSです。" },
    { type: "single", level: 2,
      q: "会社のサーバーOSに「LTS版」を選ぶ理由はどれですか?",
      choices: [
        "長期間(例: 5年)セキュリティ更新が提供されるから",
        "動作が2倍速いから",
        "GUIが豪華だから",
        "無料ではないから安心"],
      answer: [0],
      explain: "非LTSは短期間で更新が終了します。サーバーは長く使うのでLTS一択。EOL(サポート終了)管理は情シスの責任です。" },
    { type: "single", level: 2,
      q: "サーバーでCUI(コマンド操作)が主流である理由として適切でないものはどれですか?",
      choices: [
        "マウス操作の方が手順書にしやすいから",
        "GUIを描かない分、資源をサービスに回せるから",
        "SSH越しの遠隔操作・自動化と相性が良いから",
        "コマンドは誰が実行しても同じで再現性が高いから"],
      answer: [0],
      explain: "手順書にしやすいのはむしろCUI。「このコマンドを打つ」は「ここをクリック」より正確に伝わります。" },
    { type: "single", level: 2,
      q: "RHEL系とDebian系で異なる代表的なポイントはどれですか?",
      choices: ["パッケージ管理(dnf/.rpm と apt/.deb)", "TCP/IPの仕様", "ファイルという概念の有無", "SSHが使えるかどうか"],
      answer: [0],
      explain: "基本コマンドやプロトコルは共通。パッケージ管理と一部の流儀が異なります。片方を覚えればもう片方への応用は容易です。" },
    { type: "single", level: 3,
      q: "業務パッケージの動作要件に「RHEL 9 対応」とだけ書かれています。コストを抑えたい場合の現実的な選択肢はどれですか?",
      choices: [
        "RHEL互換のAlmaLinux/Rocky Linuxを検証しつつ、サポート要件次第でRHEL契約を検討する",
        "要件を無視してUbuntuに入れる",
        "Windows Serverに入れる",
        "OSなしで動かす"],
      answer: [0],
      explain: "互換OSはRHELとバイナリ互換ですが、ベンダーサポートの条件(RHEL必須か)を必ず確認。要件無視のOS選定はサポート拒否のリスクがあります。" },
  ]
};
