// Part 3 修了テスト(知識編)
window.QUIZ_DATA = {
  id: "part3-test",
  title: "Part 3 修了テスト(Linuxサーバー)※実技課題は3-13参照",
  passLine: 80,
  questions: [
    { type: "single", level: 1,
      q: "viで「保存して終了」する操作はどれですか?",
      choices: ["`:wq`", "`:q!`", "`Ctrl+S`", "`Esc`を2回"],
      answer: [0],
      explain: "`:wq`(またはZZ、:x)。`:q!`は保存せず終了です。" },
    { type: "single", level: 2,
      q: "viで設定ファイル全体のIPアドレス 10.0.0.5 を 10.0.0.6 に一括置換するコマンドは?",
      choices: ["`:%s/10.0.0.5/10.0.0.6/g`", "`/10.0.0.5 → n`", "`:replace all`", "`dd` を繰り返す"],
      answer: [0],
      explain: "%が全行、末尾gが行内全出現。実務最頻出の置換構文です。" },
    { type: "single", level: 2,
      q: "本番サーバーの設定ファイルを編集する前に必ずやることはどれですか?",
      choices: ["日付入りバックアップコピーを取る", "サービスを停止する", "chmod 777にする", "OSを再起動する"],
      answer: [0],
      explain: "「編集前バックアップ」が鉄則。壊しても即座に戻せる状態を作ってから触ります。" },
    { type: "single", level: 2,
      q: "権限 755 の意味として正しいものはどれですか?",
      choices: ["所有者rwx / グループr-x / その他r-x", "全員rwx", "所有者のみrw", "全員読み取りのみ"],
      answer: [0],
      explain: "7=rwx、5=r-x。公開ディレクトリやスクリプトの定番です。" },
    { type: "single", level: 3,
      q: "「経理グループだけ書き込める共有ディレクトリ」の正しい実装はどれですか?",
      choices: [
        "グループkeiriを作り、chown root:keiri+chmod 775(または770)を設定し、メンバーをグループに追加",
        "chmod 777 にして全員に開放",
        "経理の各ユーザー名でディレクトリを人数分作る",
        "rootのパスワードを経理全員に配る"],
      answer: [0],
      explain: "グループ設計が正道。777は改ざんし放題、パスワード共有は論外です。" },
    { type: "single", level: 2,
      q: "OS再起動後もサービスを自動起動させる設定はどれですか?",
      choices: ["`systemctl enable サービス`", "`systemctl start サービス`", "`systemctl status サービス`", "`apt upgrade`"],
      answer: [0],
      explain: "start=今すぐ、enable=次回から。両方実行して「今も再起動後も動く」状態にします。" },
    { type: "single", level: 2,
      q: "cronの「30 2 * * *」が意味する実行タイミングはどれですか?",
      choices: ["毎日 2:30", "毎日 2時30分間隔", "毎月30日の2時", "2分30秒ごと"],
      answer: [0],
      explain: "左から「分 時 日 月 曜日」。30分・2時・毎日・毎月・毎曜日=毎日2:30です。" },
    { type: "single", level: 2,
      q: "SSH公開鍵認証の正しい配置はどれですか?",
      choices: [
        "公開鍵をサーバーのauthorized_keysへ、秘密鍵は手元に保管",
        "秘密鍵をサーバーへ、公開鍵を手元に",
        "両方をサーバーへ",
        "両方をUSBメモリで全員に配布"],
      answer: [0],
      explain: "南京錠(公開鍵)は配ってよし、鍵(秘密鍵)は肌身離さず。逆配置と鍵の共有は重大事故です。" },
    { type: "single", level: 3,
      q: "sshd_configの変更作業で「自分を締め出さない」ために最も重要な行動はどれですか?",
      choices: [
        "既存SSHセッションを維持したまま別ターミナルで接続検証する",
        "変更後すぐ再起動する",
        "パスワードを紙に書いておく",
        "深夜に作業する"],
      answer: [0],
      explain: "失敗時に戻せる命綱(既存セッション)を残すのが要塞化作業の鉄則です。" },
    { type: "single", level: 2,
      q: "nginxの設定変更を無停止で反映する正しい手順はどれですか?",
      choices: ["`nginx -t` → `systemctl reload nginx`", "`systemctl stop` → 手で編集 → `start`", "OS再起動", "設定保存のみで自動反映"],
      answer: [0],
      explain: "構文チェック(-t)で事故を防いでから、無停止のreload。3点セットの curl 確認まで習慣に。" },
    { type: "single", level: 3,
      q: "Webサイトが「502 Bad Gateway」。nginx自体は動いています。最初に確認すべきはどれですか?",
      choices: [
        "背後のアプリ(PHP-FPM等)のサービス状態",
        "LANケーブル",
        "クライアントのブラウザ設定",
        "DNSレコード"],
      answer: [0],
      explain: "502=受付は生きているが奥が応答しない。upstream(背後)の生存確認が第一手です。" },
    { type: "single", level: 2,
      q: "「ディスク使用率100%でサービス停止」。犯人ディレクトリを特定するコマンドはどれですか?",
      choices: ["`du -sh /var/* | sort -h`", "`free -h`", "`top`", "`ping localhost`"],
      answer: [0],
      explain: "duで「どこが太っているか」を数値化。ログ肥大が定番犯人で、恒久対策はlogrotateです。" },
    { type: "single", level: 2,
      q: "サービスが起動失敗したときの調査コマンドの組み合わせとして正しいものはどれですか?",
      choices: [
        "`systemctl status` と `journalctl -xe`(nginxなら加えて `nginx -t`)",
        "`rm -rf /var/log` でログを消す",
        "`chmod 777 /etc` で権限を開放",
        "何もせず再起動を繰り返す"],
      answer: [0],
      explain: "status→journalctl -xeの2連コンボ+構文チェック。原因を見てから直すのが最短路です。" },
    { type: "fill", level: 2,
      q: "nginxの設定ファイルの構文チェックを行うコマンドを書いてください(sudoは省略可)。",
      answer: ["nginx -t", "sudo nginx -t"],
      explain: "`nginx -t`。エラー時はファイル名と行番号まで教えてくれます。reloadの前に必ず実行。" },
    { type: "single", level: 3,
      q: "access.logに深夜、同一IPから `/wp-login.php` へのPOSTが毎秒10回×2時間記録されていました。適切な初動はどれですか?",
      choices: [
        "攻撃(総当たり)と判断し、該当IPの遮断やレート制限・認証強化を検討する",
        "正常アクセスなので放置する",
        "サーバーの電源を切って1週間様子を見る",
        "ログファイルを削除する"],
      answer: [0],
      explain: "高頻度のログイン試行連打はブルートフォースの典型。遮断・制限・多要素化で守り、ログは証拠として保全します。" },
  ]
};
