// 3-6 パーミッション 章末クイズ
window.QUIZ_DATA = {
  id: "part3-ch06",
  title: "3-6 ユーザー・グループとパーミッション 章末クイズ",
  passLine: 70,
  questions: [
    { type: "single", level: 1,
      q: "権限 644 を記号表記にすると?",
      choices: ["rw- r-- r--", "rwx r-x r-x", "rw- rw- rw-", "r-- r-- r--"],
      answer: [0],
      explain: "6=rw-(4+2)、4=r--。所有者だけ書けて、他は読むだけ。一般ファイルの定番です。" },
    { type: "single", level: 1,
      q: "SSH秘密鍵に設定すべき権限はどれですか?",
      choices: ["600", "777", "755", "644"],
      answer: [0],
      explain: "秘密鍵は本人だけが読み書きできる600。緩いとSSHクライアント側が接続を拒否します。" },
    { type: "single", level: 2,
      q: "`-rwxr-x--- 1 root keiri script.sh` について、keiriグループ所属のtanakaさんができることは?",
      choices: ["読み取りと実行(書き込みは不可)", "読み書き実行すべて", "何もできない", "書き込みのみ"],
      answer: [0],
      explain: "グループ欄は r-x。所有者(root)はrwx、その他は---(アクセス不可)です。" },
    { type: "single", level: 2,
      q: "ディレクトリの「x」権限の意味はどれですか?",
      choices: ["その中に入れる(cdできる)", "ディレクトリを実行できる", "圧縮できる", "削除できる"],
      answer: [0],
      explain: "ディレクトリのxは「通過・進入」。rは一覧、wは中でのファイル作成・削除です。ファイルとは意味が変わる点に注意。" },
    { type: "single", level: 3,
      q: "「共有フォルダーに書き込めない」の対応として、chmod 777 が悪手である理由はどれですか?",
      choices: [
        "全ユーザーが改ざん・削除できる状態になり、原因も特定されないままだから",
        "777は文法エラーになるから",
        "動作が遅くなるから",
        "実は正しい対応だから"],
      answer: [0],
      explain: "777は「誰でも何でもできる」。正道はグループ設計(必要な人をグループに追加)で最小権限を保つことです。" },
    { type: "single", level: 2,
      q: "rootで常時ログインせず、sudoを使うべき理由として最も適切なのはどれですか?",
      choices: [
        "誤操作の影響を限定でき、誰が何を実行したか記録も残るから",
        "sudoの方が処理が速いから",
        "rootではviが使えないから",
        "sudoは無料だから"],
      answer: [0],
      explain: "常時rootは誤操作が即・全損。sudoは1コマンド単位の昇格で、auth.logに実行記録が残ります。" },
    { type: "fill", level: 2,
      q: "ファイル houkoku.txt の所有者を mirai、グループを keiri に変更するコマンドを書いてください(sudoは省略可)。",
      answer: ["chown mirai:keiri houkoku.txt", "sudo chown mirai:keiri houkoku.txt", "chown mirai.keiri houkoku.txt"],
      explain: "`chown 所有者:グループ ファイル`。グループだけならchgrp、権限はchmodです。" },
    { type: "single", level: 2,
      q: "ユーザーを既存グループに追加するコマンドはどれですか?",
      choices: ["`usermod -aG keiri suzuki`", "`groupdel keiri suzuki`", "`chmod +g keiri suzuki`", "`useradd -rm suzuki`"],
      answer: [0],
      explain: "-aG(append + Groups)で既存所属を保ったまま追加。-aを忘れると他のグループ所属が消える事故になります。" },
  ]
};
