// 3-4 基本コマンドII 章末クイズ
window.QUIZ_DATA = {
  id: "part3-ch04",
  title: "3-4 基本コマンドII 章末クイズ",
  passLine: 70,
  questions: [
    { type: "single", level: 1,
      q: "「ファイルの中身」から文字列を探すコマンドと、「ファイル名や更新日時」で探すコマンドの正しい組み合わせは?",
      choices: ["grep(中身)/ find(属性)", "find(中身)/ grep(属性)", "両方ともls", "cat と mv"],
      answer: [0],
      explain: "grep=中身、find=属性(名前・日付・サイズ)。この分業が「探す」の基本です。" },
    { type: "single", level: 2,
      q: "設定ファイルからコメント行を除いて本体だけ読むコマンドはどれですか?",
      choices: ["`grep -v \"^#\" nginx.conf`", "`grep \"^#\" nginx.conf`", "`cat -v nginx.conf`", "`rm \"#\" nginx.conf`"],
      answer: [0],
      explain: "-v は「含まない行」、^# は「行頭が#」。合わせて「コメントでない行」だけを表示します。長い設定を読む定番技です。" },
    { type: "single", level: 2,
      q: "100MBを超える巨大ファイルを探す(ディスクフル調査)コマンドはどれですか?",
      choices: ["`find / -size +100M 2>/dev/null`", "`grep -r 100MB /`", "`ls -l 100M`", "`du --over 100`"],
      answer: [0],
      explain: "findの-sizeで+100M(超)。2>/dev/nullで権限エラーの雑音を捨てるのがセットの作法です。" },
    { type: "single", level: 2,
      q: "tar.gz を「展開せずに中身を確認」するオプションの組み合わせはどれですか?",
      choices: ["`tar tzf archive.tar.gz`", "`tar czf archive.tar.gz`", "`tar xzf archive.tar.gz`", "`tar rm archive.tar.gz`"],
      answer: [0],
      explain: "t=中身一覧(test/list)。c=作成、x=展開。展開前にtで覗くのが安全な作法です。" },
    { type: "single", level: 3,
      q: "`kill 1234` が効かない暴走プロセスがあります。次の対応として正しいものはどれですか?",
      choices: [
        "最後の手段として `kill -9 1234`(強制終了)を使う",
        "最初から常に -9 を使うべきだった",
        "killは2回打つと強制になるのでもう1回打つ",
        "PCの電源を抜く"],
      answer: [0],
      explain: "既定のTERMは後片付けの猶予を与える丁寧な依頼。効かない時だけKILL(-9)。いきなり-9はデータ破損のリスクがあります。" },
    { type: "fill", level: 2,
      q: "ディスクの使用量をパーティションごとに、人間が読みやすい単位で表示するコマンドは?(コマンド+オプション)",
      answer: ["df -h"],
      explain: "`df -h`。使用率100%はサービス停止級の緊急事態。犯人探しは `du -sh` とセットで使います。" },
  ]
};
