// 2-4 DNSの仕組み 章末クイズ
window.QUIZ_DATA = {
  id: "part2-ch04",
  title: "2-4 DNSの仕組み 章末クイズ",
  passLine: 70,
  questions: [
    { type: "single", level: 1,
      q: "ドメイン名宛のメールの「届け先サーバー」を指定するDNSレコードはどれですか?",
      choices: ["MX", "A", "CNAME", "NS"],
      answer: [0],
      explain: "MX(Mail eXchanger)。メール移行時に最重要のレコードで、壊すとメールが届かなくなります。" },
    { type: "single", level: 1,
      q: "「名前→IPv4アドレス」の変換を定義するレコードはどれですか?",
      choices: ["A", "AAAA", "TXT", "MX"],
      answer: [0],
      explain: "AレコードがIPv4、AAAAがIPv6です。Webサーバー移転=Aレコード変更が定番作業です。" },
    { type: "single", level: 2,
      q: "TTLの説明として正しいものはどれですか?",
      choices: [
        "DNSの回答をキャッシュしてよい秒数",
        "ドメインの契約残り日数",
        "サーバーの生存時間",
        "パケットの最大サイズ"],
      answer: [0],
      explain: "TTL=キャッシュ有効期間。切り替え作業の前にTTLを短くしておくと、変更が早く行き渡ります。" },
    { type: "single", level: 3,
      q: "サーバー移転でAレコードを変更したのに、一部のユーザーだけ古いサーバーに接続され続けています。最も可能性が高い原因はどれですか?",
      choices: [
        "ユーザー側のキャッシュDNSにTTL期限内の古い回答が残っている",
        "新サーバーのCPU不足",
        "ユーザーのキーボード故障",
        "Aレコードは変更できないから"],
      answer: [0],
      explain: "DNS切り替えの浸透はTTL依存。事前のTTL短縮と、`ipconfig /flushdns` の案内が定番の対処です。" },
    { type: "single", level: 2,
      q: "「社内DNSがおかしいかも」というとき、外部DNSと回答を比較する切り分けコマンドはどれですか?",
      choices: ["dig @8.8.8.8 example.jp(問い合わせ先を指定)", "ping -t example.jp", "tracert 8.8.8.8", "arp -a"],
      answer: [0],
      explain: "`dig @サーバー` で聞き先を変えられます。社内DNSと外部DNSの回答が違えば、社内側の設定・障害に絞れます。" },
    { type: "single", level: 2,
      q: "hostsファイルの説明として正しいものはどれですか?",
      choices: [
        "DNSより先に参照される、端末ローカルの名前解決の対応表",
        "DNSが失敗した時だけ使われる予備ファイル",
        "Webの閲覧履歴を保存するファイル",
        "パスワードを保存するファイル"],
      answer: [0],
      explain: "hostsはDNSより優先。検証用の書き換えが残っていて「その人だけ特定サイトに行けない」事故がよく起きます。" },
  ]
};
