// 5-2 Microsoft 365管理 章末クイズ
window.QUIZ_DATA = {
  id: "part5-ch02",
  title: "5-2 Microsoft 365管理 章末クイズ",
  passLine: 70,
  questions: [
    { type: "single", level: 1,
      q: "M365の認証(ログイン)を司る基盤はどれですか?",
      choices: ["Entra ID(旧Azure AD)", "Exchange Online", "SharePoint", "OneNote"],
      answer: [0],
      explain: "Entra IDがクラウドの社員名簿+鍵束。サインインログや条件付きアクセスもここで管理します。" },
    { type: "single", level: 2,
      q: "オンプレADとEntra IDを同期させる仕組みはどれですか?",
      choices: ["Entra Connect", "Active Sync", "OneDrive同期", "BitLocker"],
      answer: [0],
      explain: "Entra Connectで同じID/パスワードを社内とクラウドで使えるハイブリッド構成になります。" },
    { type: "single", level: 3,
      q: "ハイブリッド構成で、同期対象ユーザーの部署名をEntra ID側で直接書き換えるとどうなりますか?",
      choices: [
        "次回同期でオンプレAD側の値に戻される(マスターはオンプレ側)",
        "永久に反映される",
        "両方に別の値が保存される",
        "アカウントが削除される"],
      answer: [0],
      explain: "同期構成では「どちらが正か」を意識。編集はマスター側(通常オンプレAD)で行うのが原則です。" },
    { type: "single", level: 2,
      q: "問い合わせ窓口 info@ 用のメールボックスを追加ライセンスなしで作る方法はどれですか?",
      choices: ["共有メールボックスを作成する", "架空の社員を1人契約する", "社長の個人アドレスを使う", "作れない"],
      answer: [0],
      explain: "共有メールボックスは50GBまでライセンス不要。退職者メールの保全にも使える定番機能です。" },
    { type: "single", level: 2,
      q: "「誰がこのファイルを削除したか」を調べるM365の機能はどれですか?",
      choices: ["Purviewの監査ログ検索", "Wordの変更履歴", "ゴミ箱を見るだけ", "調べる方法はない"],
      answer: [0],
      explain: "監査ログで操作者・日時・操作内容を追跡できます。有効化されているかを平時に確認しておくのが情シスの備えです。" },
    { type: "single", level: 2,
      q: "Intune(MDM)や条件付きアクセスを使いたい中小企業(300名以下)の標準的なプランはどれですか?",
      choices: ["Business Premium", "Business Basic", "個人向けMicrosoft 365", "無料プラン"],
      answer: [0],
      explain: "Premium以上でIntune・条件付きアクセス等が使えます。「全員E5」は過剰投資になりがちで、役割に応じた混在が現実解です。" },
  ]
};
