// 4-1 Windows Serverの役割 章末クイズ
window.QUIZ_DATA = {
  id: "part4-ch01",
  title: "4-1 Windows Serverの役割 章末クイズ",
  passLine: 70,
  questions: [
    { type: "single", level: 1,
      q: "Windows Serverで「社員名簿+認証の元締め」を担う役割はどれですか?",
      choices: ["AD DS(Active Directory ドメインサービス)", "DHCPサーバー", "印刷サーバー", "IIS"],
      answer: [0],
      explain: "AD DSが認証・認可の中核。止まると全社ログオン不能級の影響が出ます。" },
    { type: "single", level: 2,
      q: "RSATの説明として正しいものはどれですか?",
      choices: [
        "自分のWindows 11に入れて、手元からサーバーを管理するツール集",
        "サーバー専用のウイルス対策ソフト",
        "リモートデスクトップの別名",
        "バックアップソフト"],
      answer: [0],
      explain: "毎回サーバーへRDPせず、手元のPCからdsa.mscなどを使うのが実務の基本形です。" },
    { type: "single", level: 2,
      q: "CAL(Client Access License)の説明として正しいものはどれですか?",
      choices: [
        "サーバー本体とは別に、アクセスするユーザーまたはデバイス数分必要なライセンス",
        "サーバーを高速化する有償オプション",
        "クライアントPCのOSライセンス",
        "無料で無制限に使える権利"],
      answer: [0],
      explain: "本体ライセンス+CALの二階建て。人数分のユーザーCAL不足はライセンス監査の定番指摘です。" },
    { type: "single", level: 2,
      q: "ユーザーCALとデバイスCALの選び方として一般的なのはどれですか?",
      choices: [
        "1人がPC+スマホなど複数端末を使う会社ではユーザーCALが有利",
        "常にデバイスCALが安い",
        "両方買う必要がある",
        "CALはどちらか選べない"],
      answer: [0],
      explain: "端末数>人数ならユーザーCAL、シフト制で端末共有(人数>端末)ならデバイスCALが有利です。" },
    { type: "single", level: 1,
      q: "「dsa.msc」「gpmc.msc」のような管理画面の共通基盤はどれですか?",
      choices: ["MMC(Microsoft管理コンソール)", "BIOS", "PowerShell", "レジストリ"],
      answer: [0],
      explain: "◯◯.mscはすべてMMCのスナップイン。「ファイル名を指定して実行」から直接呼べます。" },
    { type: "single", level: 3,
      q: "Server Core(GUIなし)をドメインコントローラーに採用する利点はどれですか?",
      choices: [
        "更新が少なく攻撃面も小さいため、重要サーバーの堅牢性が上がる",
        "GUIがない分ライセンスが不要になる",
        "マウス操作で管理できる",
        "ADが2倍速くなる"],
      answer: [0],
      explain: "コンポーネントが少ない=パッチと脆弱性が減る。管理はRSAT/PowerShellで遠隔から行います。" },
  ]
};
