// 3-10 nginx入門 章末クイズ
window.QUIZ_DATA = {
  id: "part3-ch10",
  title: "3-10 nginx入門:設定の読み方 章末クイズ",
  passLine: 70,
  questions: [
    { type: "single", level: 1,
      q: "リバースプロキシの説明として最も適切なのはどれですか?",
      choices: [
        "外からのリクエストを受付窓口として受け、背後のアプリサーバーへ転送する",
        "社内から外へのWebアクセスを代理する",
        "DNSの逆引きを行う",
        "データベースを高速化する"],
      answer: [0],
      explain: "外→内の受付がリバースプロキシ。内→外の代理は(フォワード)プロキシです。方向が逆です。" },
    { type: "single", level: 2,
      q: "nginx設定の3段構造として正しいものはどれですか?",
      choices: ["http → server → location", "location → server → http", "server → http → location", "http → location → server"],
      answer: [0],
      explain: "全体(http)→どのサイト?(server)→どのURL?(location)と絞り込む入れ子構造です。" },
    { type: "single", level: 2,
      q: "server ブロックで「どのホスト名宛のリクエストを受けるか」を決めるディレクティブはどれですか?",
      choices: ["server_name", "listen", "root", "index"],
      answer: [0],
      explain: "server_nameがホスト名、listenがポート、rootがドキュメントルートです。1台で複数サイトを収容(バーチャルホスト)する鍵です。" },
    { type: "single", level: 3,
      q: "設定に `location = /login`、`location ^~ /static/`、`location ~ \\.php$`、`location /` がある場合、`/static/app.php` はどこにマッチしますか?",
      choices: [
        "`^~ /static/`(前方一致優先の宣言が正規表現より勝つ)",
        "`~ \\.php$`(正規表現が常に最優先)",
        "`= /login`",
        "どこにもマッチしない"],
      answer: [0],
      explain: "優先順位は = → ^~ → 正規表現 → 前方一致。^~が付いた前方一致は正規表現の評価をスキップさせます。" },
    { type: "single", level: 2,
      q: "設定変更後の正しい反映手順はどれですか?",
      choices: [
        "`nginx -t` で構文チェック → `systemctl reload nginx` → curlで動作確認",
        "いきなり `systemctl restart nginx`",
        "OSを再起動する",
        "設定を保存すれば自動で反映される"],
      answer: [0],
      explain: "-tで壊れた設定の反映を未然に防ぎ、reloadで無停止反映、curlで結果確認。3点セットを習慣に。" },
    { type: "single", level: 2,
      q: "Ubuntu流のnginx運用で、sites-available と sites-enabled の関係は?",
      choices: [
        "availableが定義の倉庫、enabledへシンボリックリンクを張った分だけ有効",
        "enabledが倉庫、availableが有効分",
        "両方に同じファイルをコピーする必要がある",
        "どちらも使われない"],
      answer: [0],
      explain: "有効化=ln -s、無効化=リンク削除。定義本体を消さずにON/OFFできる安全な運用です。" },
    { type: "single", level: 3,
      q: "`proxy_pass http://127.0.0.1:8080;`(末尾スラッシュなし)と `:8080/;`(あり)の違いは?",
      choices: [
        "「なし」はリクエストパスをそのまま渡し、「あり」はlocation部分を差し替えて渡す",
        "違いはない",
        "「あり」は暗号化される",
        "「なし」は構文エラー"],
      answer: [0],
      explain: "例: location /app/ で /app/x へのアクセス→「なし」なら /app/x、「あり」なら /x が背後に届きます。プロキシ404の定番原因です。" },
    { type: "single", level: 2,
      q: "HTTP(80番)へのアクセスをHTTPSへ誘導する設定はどれですか?",
      choices: [
        "`return 301 https://$host$request_uri;`",
        "`listen 443 ssl;` を80のserverに書く",
        "`root /var/www/https;`",
        "`proxy_pass https://localhost:80;`"],
      answer: [0],
      explain: "80番のserverブロックで301(恒久リダイレクト)を返すのが定石。証明書の設定は443側のserverに書きます。" },
  ]
};
